packages:
  - .

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

overrides:
  "@babel/core": 7.29.7
  picomatch: 4.0.5
  rollup: 4.62.4
  tailwindcss>nanoid: 3.3.7
  lodash: 4.18.1
  lodash-es: 4.18.1
  path-to-regexp: 0.1.13
