const campaignTokenPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** Accepts only a UUID generated by the share action; no arbitrary URL data is retained. */
export function parseCampaignToken(search: string) {
  const token = new URLSearchParams(search).get("campaign");
  return token && campaignTokenPattern.test(token)
    ? token.toLowerCase()
    : undefined;
}

/** Adds the allowlisted anonymous campaign token to a canonical shared URL. */
export function withCampaignToken(url: string, campaignToken: string) {
  if (!campaignTokenPattern.test(campaignToken)) return url;
  const sharedUrl = new URL(url);
  sharedUrl.searchParams.set("campaign", campaignToken.toLowerCase());
  return sharedUrl.toString();
}
